server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.138.139.162:3306/Piecing?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 11456asd
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath*:com/example/pintuan/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true